// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace DiamondShopSystem.API.DTO
{
    public partial class MetaltypeRequest
    {
        public int MetaltypeId { get; set; }

        public string MetaltypeName { get; set; }

        public decimal? MetaltypePrice { get; set; }

    }
}

