// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace DiamondShopSystem.API.DTO
{
    public class ProductRequest
    {
        public int ProductId { get; set; }
        public string imgUrl { get; set; }

        public string ProductName { get; set; }
        public string PP {  get; set; }

        public decimal? UnitPrice { get; set; }
    }
    public class AddProductRequest
    {
        public int CoverId { get; set; }
        public int DiamondId { get; set; }
        public decimal? UnitPrice { get; set; }
        public int MetaltypeId { get; set; }
        public int SizeId { get; set; }
        public string Pp { get; set; }
    }
    public class UpdateProductRequest
    {
        public int ProductId { get; set; }
        public int CoverId { get; set; }
        public int DiamondId { get; set; }
        public decimal? UnitPrice { get; set; }
        public int MetaltypeId { get; set; }
        public int SizeId { get; set; }
        public string Pp { get; set; }
    }
    public class TempProductSelection
    {
        public int? CoverId { get; set; }
        public int? MetaltypeId { get; set; }
        public int? SizeId { get; set; }
        public int? DiamondId { get; set; }
    }
}

