// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace DiamondShopSystem.API.DTO
{
    public class ProductRequest
    {
        public int ProductId { get; set; }
        public string imgUrl { get; set; }

        public string ProductName { get; set; }

        public decimal? UnitPrice { get; set; }
    }
}

