// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model.Models;

public partial class Address
{
    public int AddressId { get; set; }

    public string Street { get; set; }

    public string State { get; set; }

    public string City { get; set; }

    public string ZipCode { get; set; }

    public string Country { get; set; }

    public virtual Customer AddressNavigation { get; set; }
}