// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model.Models;

public partial class Category
{
    public int CategoryId { get; set; }

    public string CategoryName { get; set; }

    public virtual ICollection<Cover> Covers { get; set; } = new List<Cover>();

    public virtual ICollection<SubCategory> SubCategories { get; set; } = new List<SubCategory>();
}