// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model.Models;

public partial class CoverMetaltype
{
    public int MetaltypeId { get; set; }

    public int CoverId { get; set; }

    public string Status { get; set; }

    public virtual Cover Cover { get; set; }

    public virtual Metaltype Metaltype { get; set; }
}