// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model.Models;

public partial class CoverMetalType
{
    public int MetalTypeId { get; set; }

    public int CoverId { get; set; }

    public string Status { get; set; }

    public virtual Cover Cover { get; set; }

    public virtual MetalType MetalType { get; set; }
}