// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model.Models;

public partial class Customer
{
    public int CusId { get; set; }

    public string CusFirstName { get; set; }

    public string CusLastName { get; set; }

    public string CusPhoneNum { get; set; }

    public virtual Address Address { get; set; }

    public virtual Cart Cart { get; set; }

    public virtual User Cus { get; set; }

    public virtual ICollection<CustomerVoucher> CustomerVouchers { get; set; } = new List<CustomerVoucher>();

    public virtual Favorite Favorite { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();
}