// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model.Models;

public partial class Customer
{
    public int CusId { get; set; }

    public string CusFirstName { get; set; }

    public string CusLastName { get; set; }

    public string CusPhoneNum { get; set; }

    public int? UserId { get; set; }

    public virtual ICollection<Address> Addresses { get; set; } = new List<Address>();

    public virtual ICollection<Cart> Carts { get; set; } = new List<Cart>();

    public virtual ICollection<Favorite> Favorites { get; set; } = new List<Favorite>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();

    public virtual User User { get; set; }

    public virtual ICollection<Voucher> VouchersNavigation { get; set; } = new List<Voucher>();

    public virtual ICollection<Voucher> Vouchers { get; set; } = new List<Voucher>();
}