// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model.Models;

public partial class CustomerVoucher
{
    public int CusId { get; set; }

    public int VoucherId { get; set; }

    public virtual Customer Cus { get; set; }

    public virtual Voucher Voucher { get; set; }
}