// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model.Models;

public partial class Diamond
{


    public int DiamondId { get; set; }

    public string DiamondName { get; set; }

    public decimal CaratWeight { get; set; }

    public string Color { get; set; }

    public string Clarity { get; set; }

    public string Cut { get; set; }

    public string Shape { get; set; }

    public decimal Price { get; set; }

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}