// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model.Models;

public partial class Favorite
{
    public int FavoriteId { get; set; }

    public int Quantity { get; set; }

    public int? CusId { get; set; }

    public virtual Customer Cus { get; set; }

    public virtual ICollection<FavoriteProduct> FavoriteProducts { get; set; } = new List<FavoriteProduct>();
}