// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model.Models;

public partial class Manager
{
    public int ManagerId { get; set; }

    public string Name { get; set; }

    public string Phone { get; set; }

    public int? UserId { get; set; }

    public virtual ICollection<DeliveryStaff> DeliveryStaffs { get; set; } = new List<DeliveryStaff>();

    public virtual ICollection<SaleStaff> SaleStaffs { get; set; } = new List<SaleStaff>();

    public virtual User User { get; set; }
}