// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model.Models;

public partial class Manager
{
    public int ManId { get; set; }

    public string ManName { get; set; }

    public string ManPhone { get; set; }

    public virtual ICollection<DeliveryStaff> DeliveryStaffs { get; set; } = new List<DeliveryStaff>();

    public virtual User Man { get; set; }

    public virtual ICollection<SaleStaff> SaleStaffs { get; set; } = new List<SaleStaff>();
}