// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model.Models;

public partial class MetalType
{
    public int MetalTypeId { get; set; }

    public string MetalTypeName { get; set; }

    public string MetalTypeValue { get; set; }

    public virtual ICollection<CoverMetalType> CoverMetalTypes { get; set; } = new List<CoverMetalType>();

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}