// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model.Models;

public partial class Metaltype
{
    public int MetaltypeId { get; set; }

    public string MetaltypeName { get; set; }

    public decimal? MetaltypePrice { get; set; }

    public virtual ICollection<CoverMetaltype> CoverMetaltypes { get; set; } = new List<CoverMetaltype>();

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}