// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model.Models;

public partial class Request
{
    public int RequestId { get; set; }

    public DateTime? RequestedDate { get; set; }

    public string Context { get; set; }

    public string Status { get; set; }

    public int SStaffId { get; set; }

    public int ManId { get; set; }

    public int OrderId { get; set; }

    public virtual Manager Man { get; set; }

    public virtual Order Order { get; set; }

    public virtual SaleStaff SStaff { get; set; }
}