// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model.Models;

public partial class Shipping
{
    public int ShippingId { get; set; }

    public string Status { get; set; }

    public int? OrderId { get; set; }

    public int SaleStaffId { get; set; }

    public int? DeliveryStaffId { get; set; }

    public virtual DeliveryStaff DeliveryStaff { get; set; }

    public virtual Order Order { get; set; }

    public virtual SaleStaff SaleStaff { get; set; }
}