// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model.Models;

public partial class Size
{
    public int SizeId { get; set; }

    public string SizeName { get; set; }

    public string SizeValue { get; set; }

    public virtual ICollection<CoverSize> CoverSizes { get; set; } = new List<CoverSize>();

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}