// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model.Models;

public partial class User
{
    public int UserId { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public string Status { get; set; }

    public string Role { get; set; }

    public string RefreshToken { get; set; }

    public DateTime? RefreshTokenExpiryTime { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual DeliveryStaff DeliveryStaff { get; set; }

    public virtual Manager Manager { get; set; }

    public virtual SaleStaff SaleStaff { get; set; }
}