// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model.Models;

public partial class Voucher
{
    public int VoucherId { get; set; }

    public string Name { get; set; }

    public decimal? TopPrice { get; set; }

    public decimal? BottomPrice { get; set; }

    public string Description { get; set; }

    public DateOnly ExpDate { get; set; }

    public int? Quantity { get; set; }

    public int? Rate { get; set; }

    public virtual ICollection<CustomerVoucher> CustomerVouchers { get; set; } = new List<CustomerVoucher>();
}